### ISSUE TITLE
Fiche produit

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#10]
- supprimer le nom des qualités (ex : Floraison/Nouaison)
- Harmoniser la hauteur de l'espace blanc entre toutes les fiches produits

**Comment by RonanDrouglazet** [comment]
point 1 ok je m'en occupe 
point 2 ? Au début, il y avais une marge fixe entre le texte et les boutons, donc même "blanc" entre le texte et les boutons pour chaque produit, mais comme le texte n'a pas la même taille partout, les boutons n'était pas à la même hauteur. Tu as souhaité avoir les boutons à la même hauteur pour chaque produit -> donc le blanc n'est plus de la même taille vu que les textes ne font pas la même taille 

Il faudrait que l'on s'appel sur ce point stp, car on est plus sur photoshop là :p

**Comment by magaliebrulle** [comment]
oui on s'appelle ? :)
