### ISSUE TITLE
Mettre à jour la rubrique contact

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#11]
Créa : wetransfer dans ta boite mail
- Mise à jour de la photo de Yannick Perezzan
- Ajouter le profil de Daphné Quenot
- Plus de rollover

**Comment by RonanDrouglazet** [comment]
Mais du coup on affiche comment les informations de contact ?

**Comment by RonanDrouglazet** [comment]
si j'ajoute un profil on ne sera plus symétrique, je fait quoi ? nouvelle ligne avec un seul contact ou seconde ligne avec un contact de plus ?

**Comment by RonanDrouglazet** [comment]
ok vu avec le psd désolé
