### ISSUE TITLE
Le Menu

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#18]
Est ce que tu peux faire suivre la barre du menu sur les différentes rubrique selon la navigation ?

**Comment by RonanDrouglazet** [comment]
ok mais du coup est ce que la barre doit également aller sur la rubrique du menu qu'on survole avec la souris (comme actuellement ?) car si oui ça complique pas mal les choses :)

**Comment by magaliebrulle** [comment]
Est ce qu'on peut avoir une barre fixe qui nous indique sur quelle partie du site ou nous sommes et une seconde bar au roll pr choisir ou on veut aller ?
