### ISSUE TITLE
Vérifier la hauteur des titres de rubrique par rapport au haut du menu

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#20]

**Comment by RonanDrouglazet** [comment]
*vérifier l'espacement entre les titres et le haut de leur rubriques

**Comment by RonanDrouglazet** [comment]
l'espacement est maintenant le même partout -> 50px

**Comment by magaliebrulle** [comment]
la rubrique "une collection de marque exclusive" y à échappé :)
