### ISSUE TITLE
Ajouter packshot Ciroc (en attente bumbu)

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#22]

**Comment by RonanDrouglazet** [comment]
tu veux que j'aligne les bouteilles des deux packshot du grand slide..? Car si oui je ne peux pas, c'est l'image en elle même qu'il faudrait modifier..

**Comment by magaliebrulle** [comment]
Hier je t'ai envoyé un jpg pour placer la bouteille Ciroc, est ce que si je t'envoie le psd du peux aligner comme celui-ci ? 
il y aura juste la bouteille Bumbu en trop, on attend le stock avant de l'intégrer à la gamme

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle , peux tu m'envoyer le PSD à partir duquel tu as fait le fichier MENU.jpg qu'il y à en pièce jointe de ton mail ? Il me faudrait le psd du placement des bouteilles pour récup les ombres etc.. je peux pas partir d'un jpg ça fait beaucoup trop de bricolage pour rien

Je m'occupe du reste du produit en attendant

**Comment by magaliebrulle** [comment]
http://public.eurowinegate.com/data/public/746818.php
La bouteille June est aligné à Ciroc.

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle , je vais attendre que l'on ai le produit Bumbu pour faire ce ticket car dans le psd que tu m'as envoyé il y à la bouteille bumbu, et ce n'est franchement pas pratique de la retirer, car du coup les bouteilles à droites ne sont plus bien calé par rapport aux autres etc.. et je n'ai pas trop envie que l'on ce fasse des retours inutiles en calage alors qu'ensuite bumbu arrivera et là j'ai déjà le PSD qu'il faut ;) 

de toute manière bumbu va venir c'est sûr non ?

**Comment by magaliebrulle** [comment]
Hello Ronan, je t'envoie un nouveau psd car nous n'aurons pas Bumbu avant la mise en ligne et même d'ici quelques mois. il viendra c'est sur mais je ne sais pas quand.
psd : http://public.eurowinegate.com/data/public/f7914f.php
