### ISSUE TITLE
modif text

### ISSUE THREAD

**Issue by RonanDrouglazet** [RonanDrouglazet/Renaissance-Spirits#3]
modif textes

**Comment by magaliebrulle** [comment]
en attente des accès au code html

**Comment by RonanDrouglazet** [comment]
Tu peu aller sur ce lien pour éditer le index.html
https://github.com/RonanDrouglazet/Renaissance-Spirits/edit/master/index.html

une fois ton texte trouvé ^^ et ta modif faite, ajoute un titre et une description (ou pas) à ta modification et clique sur le bouton "commit changes", un commit est une sauvegarde en quelque sorte. N'hésite surtout pas à en faire plein de petits plutôt qu'un gros, tout simplement car on peux revenir en arrière si besoin, les annuler un par un, etc.. très pratique :) et puis ça me permettra de contrôler plus facilement tes modifs pour voir si y'a pas du html qui disparait ^^
