### ISSUE TITLE
placement claim pied de page

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#32]
"LA PASSION DE CONSTRUIRE ET DISTRIBUER DES MARQUES D'EXCEPTION"
repositionner et mettre à jour la couleur selon le psd

**Comment by magaliebrulle** [comment]
psd : http://public.eurowinegate.com/data/public/6ce882.php

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle , désolé mais la modif dans le PSD n'est pas utilisable en l'état :) 

Le texte rajouté est pixelisé / flouté donc inutilisable en tant qu'image, et je ne peux pas en récupérer la couleur non plus car le calque à été aplatie.  

De plus, impossible en CSS pure d'avoir un dégradé de couleur sur un texte, pour avoir cet effet il faut passer par une image pour être compatible tout navigateur. 

Donc sois on prend une couleur unie et là je peux faire la modif avec du "vrai" texte html, comme le reste, sois tu arrives à m'avoir ce texte en image comme dans le psd que tu m'a envoyé mais de bonne qualité

**Comment by magaliebrulle** [comment]
Compris je te trouve ca !

**Comment by magaliebrulle** [comment]
png envoyé
