### ISSUE TITLE
JUNE

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#36]
Ajouter une astérisque avec la traduction de "When life blossoms"

*Quand la vie s'épanouit

**Comment by RonanDrouglazet** [comment]
je la met ou la traduction par rapport au titre / text / bouton savoir plus stp ?

**Comment by magaliebrulle** [comment]
Bug d'affichage, l'astérisque est placé sous le texte de présentation de la marque
