### ISSUE TITLE
Finir Ciroc

### ISSUE THREAD

**Issue by RonanDrouglazet** [RonanDrouglazet/Renaissance-Spirits#4]
à envoyer

**Comment by magaliebrulle** [comment]
- packshot : envoyé
- fiche produit : envoyé
- textes et visuels : à envoyé

**Comment by RonanDrouglazet** [comment]
produit intégré, élément finaux à update cf @magaliebrulle

**Comment by magaliebrulle** [comment]
Parfum à retirer pour le moment : Pineapple et Apple
seulement 4 parfums à afficher : Ciroc vodka ultra premium, red berry, coconut et peach

Facebook : https://www.facebook.com/CirocVodkaOfficial/?fref=ts
Site Internet : https://www.ciroc.com/
