### ISSUE TITLE
Visuels Ciroc (PRIO)

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#40]
Voici les visuels pour chaque fiche produits ciroc : http://public.eurowinegate.com/data/public/ad97bc.php

**Comment by magaliebrulle** [comment]
Est ce que les bouteilles peuvent-elles être toutes de la meme taille ?

**Comment by RonanDrouglazet** [comment]
Ok je vais essayer
