### ISSUE TITLE
CIROC

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#41]
mettre à jour le visuel marque ciroc 
psd : http://public.eurowinegate.com/data/public/ce791b.php

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle, cela fait trois ou quatre fois que tu m'envois ce même PSD (AJOUT_CIROC.psb) mais l'image du visuel de marque est toujours le même dedans, je ne comprend pas trop ce qu'il y à à changer du coup ! Ou alors il y à quelque chose que je rate ^^

**Comment by magaliebrulle** [comment]
je t'ai envoyé un mail avec des screens pour être plus claire :)

**Comment by RonanDrouglazet** [comment]
Ok parfais merci, je comprend mieux, le visuel sélectionné et visible dans le psd est toujours l'ancien c'est pour ça que je ne comprenais pas, le "nouveau" était en dessous et caché :D 

Merci pour le screen ;)
