### ISSUE TITLE
Affichage page filtre (PRIO)

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#49]
pour la mise en ligne, peux-tu programmer un "capping" (de vieux souvenirs ressortent, je sais pas si c'est le bon mot ^^) sur l'affichage de la page filtre ?

**Comment by RonanDrouglazet** [comment]
Ce n'est pas exactement un capping que tu souhaite, car le simple capping c'est juste pour dire si l'utilisateur à vu la chose une fois, ou plus, on lui ré affiche pas, nous ce qu'on souhaite là c'est enregistrer un cookie si l'utilisateur clique sur "oui" et ne pas lui ré afficher le choix s'il à déjà répondu on est bien d'accord hein ? :)

**Comment by magaliebrulle** [comment]
oui :)
