### ISSUE TITLE
Tri des actus par date

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#5]
Rendre les petites boules "2015/2016" cliquables pr afficher les actu par année

**Comment by RonanDrouglazet** [comment]
ça manque un peu d'infos :) je fait quoi exactement, je slide automatiquement vers la première actu de cette année ET / OU Je masque les actus des autres années  ?

**Comment by RonanDrouglazet** [comment]
@magaliebrulle comme vu ensemble au téléphone, je n'affiche que les actus dont la date est sélectionnée, 
-> si 2016 est sélectionné je n'affiche que les actus 2016

sauf que du coup en 2016 il n'y à que deux actus, et le slide ne ressemble plus à rien.. visuellement et techniquement il à été prévu pour au moins 4 actus car il doit y en avoir une à gauche, une au milieu, une à droite :s  pour le moment je ne pense pas que ce sois une bonne idée d'intégrer cette façon de faire car un slide à deux actu c'est vraiment moche et je vois vraiment pas comment visuellement faire en sorte que ça aille

**Comment by RonanDrouglazet** [comment]
je peux mettre un exemple en ligne avec les deux actus 2016 mais comme ça ressemble à rien et que le slide est "cassé" je préfère attendre de voir si tu as besoin de "voir" visuellement ce que je te dit :) car je préfère éviter de mettre ça en ligne lol

**Comment by magaliebrulle** [comment]
Je peux te fournir 2 autres actus pour qu'on puisse faire la répartition ?

**Comment by RonanDrouglazet** [comment]
Si j'ai 4 actus minimum pour une année c'est good ! Donc oui :)

**Comment by magaliebrulle** [comment]
Très bien ! je te ponds ca aujourd'hui :)

**Comment by magaliebrulle** [comment]
envoyé : SneakersNStuff / Les Coquettes
