### ISSUE TITLE
CIROC

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#54]
Ajouter l'astérisque  à la traduction "THE ART OF CELEBRATION" 

*L'art de la célébration

**Comment by magaliebrulle** [comment]
Bug d'affichage, l'astérisque est placé sous le texte de présentation de la marque

**Comment by RonanDrouglazet** [comment]
@magaliebrulle tu peux m'envoyer un screen stp ?? J'ai testé sur desktop / mobile / tablet et tout allait bien, no comprendo :(

**Comment by magaliebrulle** [comment]
no problemo je t'envoie ca :)
pour info sur mobile ca marche très bien
