### ISSUE TITLE
Renaissance Spirit Ibéria

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#56]

**Comment by RonanDrouglazet** [comment]
on devais pas faire un new site pour ça ? Une version espagnole du site ?

**Comment by RonanDrouglazet** [comment]
@magaliebrulle

**Comment by magaliebrulle** [comment]
Si si ! on termine la version def du Français et on passe sur un new projet (Espagnol/Anglais/admin des actus) ca te va ?
