### ISSUE TITLE
Bug Excellia

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#57]

**Comment by magaliebrulle** [comment]
Dans les fiches produits, Depuis la fiche technique  Blanco au clic sur la flèche droite il n'y a plus de texte

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle, je t'envois une vidéo d'ici 5mn car je ne comprend pas ça marche très bien pour moi, la vidéo c'est pour être sûr que l'on parle de la même chose ;)
