### ISSUE TITLE
Placement textes marques

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#62]
Sur les slides de couleur, t'est-il possible d'équilibrer le positionnement des logo/claims/textes sur toutes les marques ?

Je te mets un psd avec toutes les marques : http://public.eurowinegate.com/data/public/ae0566.php

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle, ce n'est pas très clair dans le psd... Car je vois trois règles, qui sont bien calé par rapport au texte excellia, mais les règle ne corresponde pas du tout aux autres calques / slides (qui sont masqué) 

Doit-je prendre l'espacement d'excellia comme référence pour les autres ?

**Comment by magaliebrulle** [comment]
oui s'il te plait :)
