### ISSUE TITLE
Menu responsive

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#65]
quand je resize mon navigateur, le menu mobile apparait mais il n'est pas cliquable si je ne recharge pas. Est il possible de le faire cliquer sans recharger

**Comment by RonanDrouglazet** [comment]
Hello Magalie, ce n'est pas un comportement classique, ni réel :) 
Personne ne fait ça à part pour tester lol ^^  donc actuellement non je ne vais pas me pencher là dessus, je préfère faire le reste
