### ISSUE TITLE
Taille des titres

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#66]
Tu me confirme que nous sommes à 14px ?

**Comment by RonanDrouglazet** [comment]
Les titres des rubriques ? Non pas du tout, 14px c'est tout petit, de la taille d'un texte classique. On est à 2em, c'est une mesure relative, ça représente 28px en l'occurence

**Comment by magaliebrulle** [comment]
Est ce que tu peux réduire légèrement ? qu'est ce que veux dire légèrement.. 26px ?
