### ISSUE TITLE
Taille typo Marques

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#68]
Sur les textes des slides marques, tu me confirmes qu'on est à 18px

**Comment by RonanDrouglazet** [comment]
Les titres sont à 22px et les description sont à 18px oui

**Comment by RonanDrouglazet** [comment]
@magaliebrulle

**Comment by magaliebrulle** [comment]
Est ce que tu peux passer les descriptions à 16px ?
