### ISSUE TITLE
Carrousel Actu mobile

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#70]
Peux-tu inverser le sens du slide ?
quand le vais à droite, le carrousel tourne a gauche.

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle ! Oui comme la version desktop en fait :) clique sur la flèche de droite, le slide "glisse" vers la gauche (et affiche la slide qui était sur notre droite) 

Actuellement le slide desktop et mobile ont le même comportement, tu veux donc que j'inverse le sens du slide sur mobile, et que sur mobile c'est bien ça ?
