### ISSUE TITLE
Photo Actu mobile

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#71]
Peux-tu centrer les photos des actu mobile ?
2015 :
Festival de cannes (1ère avec les verres)

2016 :
Sneakernstuff
fashion week paris

**Comment by RonanDrouglazet** [comment]
Hello @magaliebrulle, pourrais tu me faire un screen ? Car moi je vois toute les images bien centrée, je ne vois donc pas quoi modifier :( 

Tu parles des images du détails de l'actu ? L'actu en elle même ?

**Comment by RonanDrouglazet** [comment]
Ok désolé @magaliebrulle, je viens de voir de quoi tu parlais (images du détails) effectivement la colonne n'est pas exactement centré, je check
