### ISSUE TITLE
Couleur textes pied de page

### ISSUE THREAD

**Issue by magaliebrulle** [RonanDrouglazet/Renaissance-Spirits#72]
Est ce que tu peux passer le texte du pied de page (sauf le claim en image que je dois te fournir) en noir avec une opacité à 20% vs blanc actuel ?

**Comment by RonanDrouglazet** [comment]
Si je met en noir à seulement 20% d'opacité en plus on ne verra plus du tout le texte, en fait tu veux que la couleur du texte sois comme dans le psd du pied de page c'est ça ? Si oui c'est simplement gris dans le psd ;) (#d1d3d4) je met cette couleur car noir à 20% d'opacité on ne vois plus le texte !
