### ISSUE TITLE
Mise en ligne du site après ajout Bumbu

### ISSUE THREAD

**Issue by simple-acces** [RonanDrouglazet/Renaissance-Spirits#93]
A mettre en ligne lundi

**Comment by RonanDrouglazet** [comment]
Tu penses qu'on peux attendre demain ? Je serais prêt ce soir pour la mise en ligne sur FTP custom !

**Comment by RonanDrouglazet** [comment]
related to https://github.com/RonanDrouglazet/OctoBoot/issues/144
